
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: feedr_development

test:
  <<: *default
  database: feedr_test


production:
  <<: *default
  database: feedr_production
  username: feedr
  password: <%= ENV['FEEDR_DATABASE_PASSWORD'] %>
